### PR TITLE
Return focus when dialog is closed to element focused before open

### LINKED ISSUE #4094: fix: keyboard focus does not return to previous element after closing FluentDialog
# 🐛 Bug Report

As in title, keyboard focus should be placed back on the element focused before the dialog was opened after it has been closed.

## 💻 Repro or Code Sample

Can be reproduced in any of the FluentDialog examples -> https://www.fluentui-blazor.net/Dialog

## 💁 Possible Solution

Register an onkeydown listener on both the first menu item (if one exists) and the menu button. If focus is on the menu button, tab will place focus on the first item in the menu. If focus is on the first menu item, a shift-tab will place focus back on the button.

Save a reference to the element currently focused during dialog open, in the dialog service. Focus it again during close.

I will follow up with a fix tomorrow.

## 🔦 Context

https://github.com/dotnet/aspire/issues/10119

### PR DESCRIPTION
**Pull request by adamint**
# Pull Request

## 📖 Description

Exposes two functions to get the focused element and set focus in `dialog-utils.js`. Uses that in the dialog provider to get the focused element before the dialog is created (which messes with focus), and then to reset focus after close. Dialog doesn't always close immediately, so I added a small delay.

Before:

https://github.com/user-attachments/assets/d8edbe5c-a111-45bc-bb19-bf6c076a1234

After:

https://github.com/user-attachments/assets/ac758bea-aafc-4a28-b648-1dd7ddf3d7a8

### 🎫 Issues

Fixes #4094

## 👩‍💻 Reviewer Notes

You can test this using the Dialog samples.

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fluentui-blazor/blob/master/docs/contributing.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have added [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for my new component
- [x] I have modified an existing component
- [x] I have validated the [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component

### CODE REVIEW

File: src/Core/wwwroot/js/dialog-utils.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export function getActiveElement() {
```
Comment (dvoituron) [inline src/Core/wwwroot/js/dialog-utils.js]: We cannot accept JavaScript code in wwwroot files. You must move your code to a `FluentDialogProvider.razor.js` file. You will find an example in the `FluentButton` button.

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs [hunk 2]
```diff
@@ -40,24 +50,47 @@ protected override void OnInitialized()
...
+        return await Task.Run(async () =>
+        {
+            var previouslyFocusedElement = await _module.InvokeAsync<IJSObjectReference>("getActiveElement");
+
+            DialogInstance dialog = new(dialogComponent, parameters, content, previouslyFocusedElement);
             dialogReference.Instance = dialog;
 
             _internalDialogContext.References.Add(dialogReference);
-            InvokeAsync(StateHasChanged);
+            await InvokeAsync(StateHasChanged);
```
Comment (dvoituron) [inline src/Core/Components/Dialog/FluentDialogProvider.razor.cs]: Why did you changed this line?

File: src/Core/Components/Dialog/Services/DialogInstance.cs [hunk 3]
```diff
@@ -20,6 +23,8 @@ public DialogInstance(Type? type, DialogParameters parameters, object content)
 
     public object Content { get; internal set; } = default!;
 
+    public IJSObjectReference PreviouslyFocusedElement { get; }
```
Comment (dvoituron) [inline src/Core/Components/Dialog/Services/DialogInstance.cs]: Can you change this property to `internal`?

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs [hunk 4]
```diff
@@ -4,20 +4,30 @@
...
     private IDialogService DialogService { get; set; } = default!;
 
     [Inject]
     private NavigationManager NavigationManager { get; set; } = default!;
 
+    [Inject]
+    private IJSRuntime JSRuntime { get; set; } = default!;
+
+    [Inject]
+    private LibraryConfiguration LibraryConfiguration { get; set; } = default!;
```
Comment (dvoituron) [inline src/Core/Components/Dialog/FluentDialogProvider.razor.cs:30]: Why did you add this property?

File: src/Core/wwwroot/js/dialog-utils.js [hunk 5]
```diff
@@ -0,0 +1,7 @@
...
+    return document.activeElement
+}
+
+export function focusElement(element) {
```
Comment (dvoituron) [inline src/Core/wwwroot/js/dialog-utils.js]: Yo avoid side effect in some situations, can you test if the element is defined?
```js
if (element) {
  element.focus();
}
```

**Review by dvoituron — CHANGES_REQUESTED** [review]

File: src/Core/wwwroot/js/dialog-utils.js (hunk 1 above)
Comment (adamint) [reply src/Core/wwwroot/js/dialog-utils.js]: I thought scoped JS file import wasn’t supported outside of a blazor component? Since unlike FluentButton, the provider isn’t a component, I didn’t see another place to put this file.

or do I misunderstand?

Comment (adamint) [reply src/Core/wwwroot/js/dialog-utils.js]: edit: I was misunderstood, apologies! It is a component 😄

**Comment by MarvinKlein1508** [comment]
Just because I'm curious: what happens if I open the dialog via code somehow? Which element will be focused then?

For example in my case I open a modal directly in `OnParameterSetAsync` when a certain condition is invalid.

**Comment by vnbaaij** [comment]
I would say nothing happens then. I think this is done when the code from @dvoituron 's last review comment gets added

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs (hunk 2 above)
Comment (adamint) [reply src/Core/Components/Dialog/FluentDialogProvider.razor.cs]: Reverted

File: src/Core/Components/Dialog/Services/DialogInstance.cs (hunk 3 above)
Comment (adamint) [reply src/Core/Components/Dialog/Services/DialogInstance.cs]: Done!

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs (hunk 4 above)
Comment (adamint) [reply src/Core/Components/Dialog/FluentDialogProvider.razor.cs:30]: It's used in the module import

File: src/Core/wwwroot/js/dialog-utils.js (hunk 5 above)
Comment (adamint) [reply src/Core/wwwroot/js/dialog-utils.js]: Done!

**Comment by adamint** [comment]
> Just because I'm curious: what happens if I open the dialog via code somehow? Which element will be focused then?
> 
> For example in my case I open a modal directly in `OnParameterSetAsync` when a certain condition is invalid.

Whatever element that is currently focused at the time that `OnParameterSetAsync` is called. In my opinion, focus should always return back to the previous element so that users of screen readers can continue to navigate the page in order.

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs [hunk 6]
```diff
@@ -40,20 +51,43 @@ protected override void OnInitialized()
...
-        return await Task.Run(() =>
+        if (_module is null)
         {
-            DialogInstance dialog = new(dialogComponent, parameters, content);
+            throw new InvalidOperationException("JS module is not loaded.");
+        }
+
+        return await Task.Run(async () =>
+        {
+            var previouslyFocusedElement = await _module.InvokeAsync<IJSObjectReference>("getActiveElement");
```
Comment (dvoituron) [inline src/Core/Components/Dialog/FluentDialogProvider.razor.cs:88]: You will find in the documentation: "If the focused element is within a document tree that's not descended from the current document (for example, the focused element is in the main document, and the invoking document is an embedded iframe), then this will be null."
https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

So, previouslyFocusedElement can be null and you need to manage this case in `DialogInstance` and all methods called.

File: src/Core/Components/Dialog/Services/DialogInstance.cs [hunk 7]
```diff
@@ -22,6 +25,8 @@ public DialogInstance(Type? type, DialogParameters parameters, object content)
 
     public DialogParameters Parameters { get; internal set; }
 
+    internal IJSObjectReference PreviouslyFocusedElement { get; }
```
Comment (dvoituron) [inline src/Core/Components/Dialog/Services/DialogInstance.cs]: This property must be nullable. See my [other comment](https://github.com/microsoft/fluentui-blazor/pull/4095/files#r2311858864)

**Comment by dvoituron** [comment]
This new feature should be added to the “dev-v5” branch for the new Dialog component.

File: src/Core/Components/Dialog/Services/DialogInstance.cs (hunk 7 above)
Comment (vnbaaij) [reply src/Core/Components/Dialog/Services/DialogInstance.cs]: Changed by me

File: src/Core/Components/Dialog/FluentDialogProvider.razor.cs (hunk 6 above)
Comment (vnbaaij) [reply src/Core/Components/Dialog/FluentDialogProvider.razor.cs:88]: I've changed this in DialogInstance

**Review by dvoituron — APPROVED** [review]

**Comment by vnbaaij** [comment]
@microsoft-github-policy-service agree
