### PR TITLE
[dev-v5][Nav] Fix using WithColor() with icons in Nav

### LINKED ISSUE #4704: [dev-v5] fix: FluentNavItem is not considering custom icon colors
# 🐛 Bug Report

`FluentNavItem` is not applying an icon color when one is specified via `.WithColor`

## 💻 Repro or Code Sample
```razor
<FluentNav>
    <FluentNavItem Href="/Account/Logout" IconRest="@(new Icons.Regular.Size20.SignOut().WithColor(Color.Error))">Logout</FluentNavItem>
</FluentNav>
```

## 🤔 Expected Behavior

I expect the icon to be red.

## 😯 Current Behavior

Icon is in brand color.

## 🌍 Your Environment

* OS & Device: Windows 11 64 Bit
* Browser latest Firefox, Edge & Chrome
* latest dev-v5 branch

### PR DESCRIPTION
**Pull request by vnbaaij**
You can now use `WithColor()` on `IconRest` and `IconActive` in both `FluentNavItem` and `FluentNavCategory`. Previously the icons always used `Color.Primary`/`Color.Default`

Example has been updated to use this new functionality. Unit test have been added to verify the new behavior.

Fix #4704

### CODE REVIEW

File: tests/Core/Samples/Icons.cs [hunk 1]
```diff
@@ -12,6 +12,12 @@ public static class Icons
 
     public static readonly Icon PresenceAvailable = new Samples.PresenceAvailable();
 
+    /// <summary>Creates a fresh <c>Info</c> icon instance, avoiding mutation of the shared <see cref="Info"/> static.</summary>
+    public static Icon NewInfo() => new Samples.Info();
```
Comment (dvoituron) [inline tests/Core/Samples/Icons.cs:16]: Please, add `readonly`

File: examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor [hunk 2]
```diff
@@ -11,7 +11,7 @@
                Density="@Density">
 
         <!-- Navigation Items -->
-        <FluentNavItem Href="/Nav" IconRest="@((new Icons.Regular.Size20.Board()))" IconActive="@((new Icons.Filled.Size20.Board()))">
+        <FluentNavItem Href="/NavX" IconRest="@((new Icons.Regular.Size20.Board().WithColor(Color.Error)))" IconActive="@((new Icons.Filled.Size20.Board().WithColor(Color.Success)))">
```
Comment (dvoituron) [inline examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor]: Why this `NavX` ?

**Review by dvoituron — CHANGES_REQUESTED** [review]

File: tests/Core/Samples/Icons.cs (hunk 1 above)
Comment (vnbaaij) [reply tests/Core/Samples/Icons.cs:16]: They need to be invocable like a method. They can't be `readonly` and have '`=>`'. Then it needs to be '`=`' and they cannot be used like a method anymore.

File: examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor (hunk 2 above)
Comment (vnbaaij) [reply examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor]: Oops, was a test case

File: src/Core/Components/Nav/FluentNavCategory.razor [hunk 3]
```diff
@@ -13,7 +13,10 @@
 			@attributes="@AdditionalAttributes">
 		@if (Owner.UseIcons && IconRest is not null)
 		{
-			<FluentIcon Value="@(_isActive ? IconActive ?? IconRest : IconRest)" Class="icon" Color="@(_isActive ? Color.Primary : Color.Default)" />
+            var customColor = _isActive ? (IconActive?.Color ?? IconRest.Color) : IconRest.Color;
```
[the remark this answers is not in the document]
Comment (vnbaaij) [reply src/Core/Components/Nav/FluentNavCategory.razor:16]: Not true, it is already in a code block because of the @if

File: examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor (hunk 2 above)
[the remark this answers is not in the document]
Comment (vnbaaij) [reply examples/Demo/FluentUI.Demo.Client/Documentation/Components/Nav/Examples/NavDefault.razor]: Already fixed

**Review by dvoituron — APPROVED** [review]
